name: Databricks Demo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup dbx CLI
        run: |
          sudo apt install -y jq unzip
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Authenticate
        run: |
          databricks configure
        env:
          DATABRICKS_HOST: "${{ secrets.DATABRICKS_HOST }}"
          DATABRICKS_TOKEN: "${{ secrets.DATABRICKS_TOKEN }}"

      - name: Deploy Infra + Run
        run: bash deployments/dbx/deploy.sh

