name: Build & Push React App to ACR

on:
    workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/react-front  # adjust if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: identity

    - name: Login to ACR
      run: |
        az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}

    - name: Extract short SHA
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

    - name: Build & Push Docker image to ACR
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}/react-app:${SHORT_SHA} .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}/react-app:${SHORT_SHA}
