name: Build & Push Go App to ACR

on:
    workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image to ACR
    runs-on: ubuntu-latest
    permissions:
    #   id-token: write is required for Azure Login with OIDC
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ./apps/go-api

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: |
        az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}

    - name: Extract short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

    - name: Build & Push Docker Image to ACR
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}/go-api:${SHORT_SHA} .
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}/go-api:${SHORT_SHA}

