name: Test Azure Login

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    permissions:
    #   id-token: write is required for Azure Login with OIDC
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Show current Azure subscription
        run: az account show
